### ISSUE TITLE
Enable direct request, e. g. per Environment variable

### ISSUE THREAD

**Issue by b-eyselein** [OCR4all/LAREX#129]
When building the docker image a feature was enabled per 

```bash
sed -i 's/#directrequest:<value>/directrequest:enable/' /opt/OCR4all_Web/submodules/LAREX/Larex/src/main/webapp/WEB-INF/larex.config
```

This is not done anymore while building the docker image, but seems to be neccessary for certain functionality.

**Comment by NesbiDevelopment** [comment]
I'm currently working on it.
The feature is included and I'm currently about to test everything.

The change should be live in the next hour.

**Comment by NesbiDevelopment** [comment]
Larex now supports an environment variable to define define another path to the larex.config.

Larex automatically tests for a "LAREX_CONFIG" variable and checks if it points to an existing file.
It will, if the file exists use that configuration file instead of the default file in "LAREX/src/main/webapp/WEB-INF/larex.config"

The changes are active starting with cc86b40
