### ISSUE TITLE
open other book symbol is gone

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#180]
With current `dev` and `staging`, the "directory" symbol in the upper left navigation area is gone. It has been replaced (or shadowed?) with a pop-up menu for the page selection. The latter is redundant IMHO, because there is already a thumbnail preview-based navigation panel to the left for that. But the former is very important to quickly navigate from document to document (esp. if they are not as large as a book).

![bug-navigation-book](https://user-images.githubusercontent.com/38561704/82436646-719b5a80-9a96-11ea-8b47-c66238bc0524.png)

**Comment by maxnth** [comment]
We're currently working on adding a property to the LAREX config file which will determine whether LAREX is used in interaction with OCR4all or not. 
Depending on this certain UI elements won't be shown, as they're not really useful when using LAREX with OCR4all, e.g. the directory symbol.
The directory icon will be "readded" by default before releasing the new version, sorry for the inconvenience at the moment.

>The latter is redundant IMHO, because there is already a thumbnail preview-based navigation panel to the left for that.

We added it because it was requested by several users and makes it easier to navigate to a certain page when having projects with several hundred pages, as hovering repeatedly over the thumbnail to determine the current page number while scrolling can be a bit annoying.
But if it's unnecessary for certain use cases we could think about just letting the user "disable" it in the config file as well.

**Comment by bertsky** [comment]
> We added it because it was requested by several users and makes it easier to navigate to a certain page when having projects with several hundred pages, as hovering repeatedly over the thumbnail to determine the current page number while scrolling can be a bit annoying.

Understood. Another benefit would be that you can directly see just where you are currently (without hovering the current preview image).

But IMO the fixed 100px width is just way to small, at least for non-numeric page numbers (as happens when importing existing PAGE-XML annotations).

So if I can make a wish, how about having **both** the directory button and a (larger) page-selection menu?

**Comment by maxnth** [comment]
>But IMO the fixed 100px width is just way to small, at least for non-numeric page numbers (as happens when importing existing PAGE-XML annotations).

I totally agree.
I have to admit that I only tested the feature either in combination with OCR4all or stand-alone with data from OCR4all. In both cases all page names consist out of exactly 4 digits. 
Will get fixed before release.

**Comment by maxnth** [comment]
The icon will now be displayed again (if OCR4all mode isn't set in the config) since commit 0e8caf51e03993c6e73f86e8d34e48819a3995b8

**Comment by bertsky** [comment]
> > But IMO the fixed 100px width is just way to small, at least for non-numeric page numbers (as happens when importing existing PAGE-XML annotations).
> 
> I totally agree.
> I have to admit that I only tested the feature either in combination with OCR4all or stand-alone with data from OCR4all. In both cases all page names consist out of exactly 4 digits.
> Will get fixed before release.

I have a fix for this locally. Unfortunately, you cannot see much in the diff of the single-line CSS source files (but I can make a PR if you want). Here's what I changed:

- in `webapp/resources/css/viewer.css`: change `.menuPageSelector input` from `width:100px !important` to `width:40%` and from `text-indent:34%` to `text-indent:4%` (but maybe this should be center alignment instead)
- in `webapp/resources/css/materialize.min.css`: change `.select-wrapper input.select-dropdown` from `width:100%` to `width:300px`
