### ISSUE TITLE
Saving during Ground Truth Production is confusing

### ISSUE THREAD

**Issue by b2m** [OCR4all/LAREX#226]
I am in the _Ground Truth Production_ step in OCR4All and switching between the modes _Segmentation_, _Lines_ and _Text_.

When I forget to press save between switching the modes the saved data becomes inconsistent resulting in data loss.

Example steps to reproduce (reduced to minimum):

1. Load Project
1. Perform _Preprocessing_
1. Go to _Ground Truth Production_
1. Add segments (**no save**)
1. Add lines (**no save**)
1. Add text and save
1. Check Page XML => no Page XML created.

**Expectation:** I would expect either a automatic save or forced save (changes present) between mode switching. Alternatively pressing save e.g. in _Text_ mode should also save changes from _Line_ and _Segment_ mode.

**Version:** Larex was used via docker and the current ls6uniwue/ocr4all:**latest**.

**Comment by maxnth** [comment]
Thanks for these bug reports, they're really helpful as most users/testers had semi automatic use cases and most likely just used the `Lines` tab for altering/removing/adding lines after the automatic line segmentation was applied, so these kind of bugs flew under our radar until now.

This specific bug is triggering because LAREX – for some reason – expects a set reading order for text lines and is crashing when no line reading order exists. This obvious shouldn't happen and I'll look into fixing this ASAP.

**Comment by b2m** [comment]
Well, I also would prefer (semi-)automatic use cases =)

But to understand how things work (or why they are not working) you sometimes have to try simple things.

Also most of the Tools (OCR4All, OCR-D*) are developed with a focus on libraries and therefore books.
In the archive we have a more diverse selection of material to process.

**Comment by b2m** [comment]
I was trying to reproduce the error using the current ls6uniwue/ocr4all:**nightly** docker image containing
 - OCR4All: 0.5-RC2
 - Larex: 0.5-RC3

As described the reported bug is no longer reproducible, and therefore considered fixed.

Thank you =)
