### ISSUE TITLE
Help - Segments

### ISSUE THREAD

**Issue by IlaCode** [OCR4all/LAREX#243]
![larexexample](https://user-images.githubusercontent.com/74908338/101333398-da9dc080-3876-11eb-870a-50b1d2a6666d.png)

Hi,
I'm trying to segment pages of a book. Why does this attached page see it as an image? Am I wrong to use LAREX? thanks a lot

**Comment by maxnth** [comment]
>Why does this attached page see it as an image?

Most likely because of the noise surrounding the the actual page content which "confuses" the underlying algorithm.

>Am I wrong to use LAREX?

I wouldn't say so, there are both internal and external ways to improve the results.

Within LAREX itself setting a `Region of Interest` (`RoI` in the toolbar) or using `ignore` regions to mark the e.g. book fold/book cover should vastly improve the results of the auto segmentation.

When dealing with "raw" scans it's probably advisable to preprocess the images before using them with stand-alone LAREX though.
Using a tool like [ScanTailor](https://scantailor.org/) or [ScanTailor Advanced](https://github.com/4lex4/scantailor-advanced/releases) (or any other similar tool) to (semi)automatically remove borders (or any other noise), dewarp or deskew the scans should lead to vastly improved results.
