### ISSUE TITLE
Automatic polygon simplification

### ISSUE THREAD

**Issue by maxnth** [OCR4all/LAREX#286]
Allow automatically simplifying existing polygons using e. g. the  Douglas–Peucker algorithm

**Comment by bertsky** [comment]
> Allow automatically simplifying existing polygons using e. g. the Douglas–Peucker algorithm

Very useful indeed. However, I'd recommend _against_ naive implementation of Douglas-Peucker, because that might change the topology and its result may depend on the order / starting-point of the coordinate ring. Shapely offers a [preserve_topology option](https://shapely.readthedocs.io/en/stable/manual.html#object.simplify) against this. In OCR-D core's PAGE validator (which ensures both self-validity and consistency between parent and child), [this is how](https://github.com/OCR-D/core/blob/d4a853964ce468a2c0eb6be2004c15441fbd206f/ocrd_validators/ocrd_validators/page_validator.py#L198-L211) we deal with it.

**Comment by maxnth** [comment]
merged

**Comment by bertsky** [comment]
#295 is fantastic – but only applies to the region level. Often, the most complicated polygons (and most editing effort) is on the line level. Any chance we can get that, too?

**Comment by bertsky** [comment]
This can be closed – thanks @chaddy314!
