### ISSUE TITLE
AlternativeImages are all moved to page level when saving

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#290]
I just found that the new PAGE-XML editing facility still has one bug: it does not retain `AlternativeImage` under their original segment (which could be region, line, word or even glyph), but moves them all to the top (page) level.

This is a big problem for OCR-D especially. (It means a region or line crop will be mistaken for a page image.)

**Comment by maxnth** [comment]
Finally got the time to look into it and the PR [here](https://github.com/PRImA-Research-Lab/prima-core-libs/pull/21) should hopefully fix this.
Will push a custom build of PrimeDla to the LAREX dev branch after some further testing.

**Comment by maxnth** [comment]
Updated PrimaDla in [31258ab](https://github.com/OCR4all/LAREX/commit/31258ab0aa8a50c3559ce7a3f7b4101c6b9426d0) to include the fix for this issue.
Non page-level alternative images should now be kept when updating / writing the PAGE XML (not when changing region types (e. g. from `TextRegion` to `ImageRegion`) yet but this is part of another issue we have to address).
